name: LinuxFunMachine

on:
  workflow_dispatch:
      inputs:
        acc:
          default: '0'
  push:
      
jobs:
  Parse:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip install undetected-chromedriver
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
    - name: Parser
      run: python script.py ${{inputs.acc}}
