name: FunMachine

on:
  workflow_dispatch:
      inputs:
        acc:
          default: '0'
  push:
      
jobs:
  Parse:
    runs-on: windows-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip install undetected-chromedriver
    - name: Install Chrome
      shell: pwsh
      run: |
        Start-Process -FilePath ChromeSetup.exe -Args “/silent /install” -Verb RunAs -Wait;
    - name: Parser
      run: python script.py ${{inputs.acc}}
