name: FunMachine

on:
  workflow_dispatch:
      inputs:
        acc:
          default: '0'
  #push: 
      
jobs:
  Parse:
    runs-on: windows-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip install undetected-chromedriver
    - name: Update Chrome
      run: |
        & "C:\Program Files (x86)\Google\Update\GoogleUpdate.exe" /ua /installsource scheduler
    - name: Parser
      run: python script.py ${{inputs.acc}}
