name: FunMachine

on:
  workflow_dispatch:
      inputs:
        acc:
          default: '0'
  push:
      
jobs:
  Parse:
    runs-on: windows-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip install undetected-chromedriver
    - name: Install Chrome
      shell: pwsh
      run: |
        $Path = $env:TEMP;
        $Installer = “chrome_installer.exe”;
        Invoke-WebRequest “https://www.google.com/intl/ru/chrome/thank-you.html?standalone=1&statcb=1&installdataindex=empty&defaultbrowser=0#" -OutFile $Path\$Installer;
        Start-Process -FilePath $Path\$Installer -Args “/silent /install” -Verb RunAs -Wait;
        Remove-Item $Path\$Installer
    - name: Config Proxy
      run: netsh winhttp set proxy 196.219.202.74:8080
    - name: Parser
      run: python script.py ${{inputs.acc}}
